version: '3'
services:
  # Signature scan service (default behavior)
  hub-load-signature:
    image: hubload-latest
    environment:
      - SCAN_TYPE=SIGNATURE_SCAN
      - BD_HUB_URL=https://dummy
      - API_TOKEN=dummy==
      - SYNCHRONOUS_SCANS=no
      - MAX_SCANS=100
      - MAX_CODELOCATIONS=1
      - MAX_VERSIONS=1
      - RANDOM_SCANS=no
      - FIXED_COMPONENTS=20
      - SNIPPETS=no
      - STRING_SEARCH=no
      - DEBUG=no
      - TEST_DURATION=1
    command: /home/hub_load/submit_scans_fixed.sh
    deploy:
      restart_policy:
        condition: none
      mode: replicated
      replicas: 2
      update_config:
        delay: 4s

  # Binary scan service
  hub-load-binary:
    image: hubload-latest
    environment:
      - SCAN_TYPE=BINARY_SCAN
      - BD_HUB_URL=https://dummy
      - API_TOKEN=dummy==
      - SYNCHRONOUS_SCANS=no
      - MAX_SCANS=100
      - MAX_CODELOCATIONS=1
      - MAX_VERSIONS=1
      - RANDOM_SCANS=no
      - FIXED_COMPONENTS=1
      - DEBUG=no
      - TEST_DURATION=1
    command: /home/hub_load/submit_scans_fixed.sh
    deploy:
      restart_policy:
        condition: none
      mode: replicated
      replicas: 1
      update_config:
        delay: 4s

  # Container scan service
  hub-load-container:
    image: hubload-latest
    environment:
      - SCAN_TYPE=CONTAINER_SCAN
      - BD_HUB_URL=dummy
      - API_TOKEN=dummy==
      - SYNCHRONOUS_SCANS=no
      - MAX_SCANS=100
      - MAX_CODELOCATIONS=1
      - MAX_VERSIONS=1
      - RANDOM_SCANS=no
      - FIXED_COMPONENTS=1
      - DEBUG=no
      - TEST_DURATION=1
    command: /home/hub_load/submit_scans_fixed.sh
    deploy:
      restart_policy:
        condition: none
      mode: replicated
      replicas: 1
      update_config:
        delay: 4s